/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matematicadiscreta;

import Classes.Conjunto;
import java.util.ArrayList;

/**
 *
 * @author pedro.def
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    ArrayList<Conjunto> Conjuntos = new ArrayList();
    public Index() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Cbx(){
        for(Conjunto conj:Conjuntos ){
            cbxConjuntos.addItem(conj.getNome());
            cbxConjuntos1.addItem(conj.getNome());
            cbxConjuntos2.addItem(conj.getNome());
            cbxConjuntos3.addItem(conj.getNome()); 
            cbxConjuntos5.addItem(conj.getNome()); 
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfElemento = new javax.swing.JTextField();
        cbxConjuntos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfSaida = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cbxConjuntos3 = new javax.swing.JComboBox<>();
        cbxConjuntos1 = new javax.swing.JComboBox<>();
        tfOperacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cbxConjuntos2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbxConjuntos5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Conjunto : "));

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Conjunto");

        jButton1.setText("Criar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Atualizar Cbbox");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 280, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserir Elementos no Conjunto : "));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(tfElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, 120, -1));

        jPanel2.add(cbxConjuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 47, 120, -1));

        jButton2.setText("Inserir  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 130, -1));

        jLabel2.setText("Selecionar Conjunto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 140, -1));

        jLabel3.setText("Elemento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 73, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 290, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados :"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(tfSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 310, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.add(cbxConjuntos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 90, -1));

        jPanel4.add(cbxConjuntos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, -1));
        jPanel4.add(tfOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 90, -1));

        jLabel4.setText("Digite um Elemento:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel6.setText("Conjunto 2 ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jButton5.setText("Pertence");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 100, -1));

        jButton6.setText("Contém");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        jPanel4.add(cbxConjuntos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, -1));

        jLabel7.setText("Conjunto 1 ");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, -1));

        jLabel8.setText("Conjunto :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 80, 20));

        jButton7.setText("Subconjunto");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 110, -1));

        jButton8.setText("Subconjunto próprio");
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 160, -1));

        jButton9.setText("União");
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jButton10.setText("Intersecção");
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jButton11.setText("Complemento");
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jButton12.setText("Diferença");
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel9.setText("Verificar a Existencia de um Elemento em Determinado Conjunto:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel10.setText("Operações entre conjuntos:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jButton13.setText("Conjunto das Partes");
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 580, 250));

        jButton3.setText("Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 120, -1));

        getContentPane().add(cbxConjuntos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 120, -1));

        jLabel5.setText("Escolha o Conjunto ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 130, -1));

        jLabel11.setText("Imprimir um Determinado Conjunto:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Conjunto Conj = new Conjunto(tfNome.getText());
        Conjuntos.add(Conj);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           for(Conjunto conj:Conjuntos ){
               if(cbxConjuntos.getSelectedItem().equals(conj.getNome())){
                   conj.inserir(tfElemento.getText());
               }
           }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            for(Conjunto conj:Conjuntos ){
               if(cbxConjuntos1.getSelectedItem().equals(conj.getNome())){
                   tfSaida.setText(conj.imprimir());
               }
           }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cbxConjuntos.removeAll();
        cbxConjuntos1.removeAll(); 
        cbxConjuntos2.removeAll();
        cbxConjuntos3.removeAll();
        cbxConjuntos5.removeAll();
        Cbx();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        for(Conjunto conj:Conjuntos ){
               if(cbxConjuntos3.getSelectedItem().equals(conj.getNome())){
                   String elemento = tfOperacao.getText();
                   if (conj.pertence(tfOperacao.getText()).equals(true)){    
                       tfSaida.setText(elemento + " ∈ "+ conj.getNome());
                   }
                   else{
                        tfSaida.setText(elemento + " ∉ "+ conj.getNome());
                   }
                  
               }
           }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Conjunto conj1 = null;
        Conjunto conj2 = null;
        
        for(Conjunto conj:Conjuntos ){
            if(cbxConjuntos1.getSelectedItem().equals(conj.getNome())){
                conj1 = conj;
            }
            if(cbxConjuntos2.getSelectedItem().equals(conj.getNome())){
                conj2 = conj;
            } 
          }
        if(conj1.contem(conj2.getElementos()).equals(true)){
            tfSaida.setText("contem");
            
        }
        else{
            tfSaida.setText("não contem");
        }    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nome = "a";
        Conjunto conj1 = new Conjunto("a");
        conj1.inserir("a");
        conj1.inserir("b");
        conj1.inserir("c");
        conj1.inserir("d");
        conj1.ConjuntoDasPartes();
        
 
        
        
       
        
        
                

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxConjuntos;
    private javax.swing.JComboBox<String> cbxConjuntos1;
    private javax.swing.JComboBox<String> cbxConjuntos2;
    private javax.swing.JComboBox<String> cbxConjuntos3;
    private javax.swing.JComboBox<String> cbxConjuntos5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tfElemento;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfOperacao;
    private javax.swing.JTextField tfSaida;
    // End of variables declaration//GEN-END:variables
}
